# -*- coding: utf-8 -*-
"""Alper_Acar_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1joPh_k3dz2I5_EpWtuggXJ70qWN4Hx5X

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""

Alper Acar
student number:1722441

"""Describe what an algorithm is."""

An algorithm is a way to solve and improve computer sciences, Kind of series of mathematical transformations
;Basically its not the hand decisive and know for which side of coin will appear (Heads or tails),it is the hand just flip the coin a set
of steps works with methodical steps that can be used to make
calculations, resolve problems and
reach decisions. for example Google uses an algorithms to identify pages or visuals
;For example ''Google Visuals'' as i know that it uses 4000 line code to identify same faces an alghorithm
or an alghoritm can find same kind of voices with parameters 
it network of pages to identify the
individual pages that are most relevant .

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

there is a difference between alghrotims and Brute force is both of them usable to achive a solutioun 
Brute force as an understandable its trying one by one with informations that you give 
on the other hand alghorithms can generate 
if the rules are given alghorithms can create solutiouns with complex way not one by one it generates

"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""

İnfo = {'name':'Alper'
       'surname':'Acar'
       'age':23}

"""Create a python dictionary for your name surname and year of birth."""

info = {'name':'Alper','surname':'Acar','year of birth':'1992'}
print(info['surname'])

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

name ='Alper Acar'
name =[0]
if name [0] =='a|A':
  print ('my initial is a!')
  
else:
  print('nothing else matters')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

surname = 'Acar'
if len(surname)%3 == 1:
  print('it is divisible')

"""Change your year of birth to 2678."""

info.update({'birth year':'2678'})
print(info['birth year'])

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""



"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""